table:
  name: token_transactions
  schema: public
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - user_id
        - wallet_address
        - amount
        - type
        - status
        - source
        - source_id
        - tx_hash
        - block_number
        - created_at
        - updated_at
      filter:
        user_id:
          _eq: X-Hasura-User-Id
