table:
  name: physical_activities
  schema: public
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - user_id
        - type
        - title
        - description
        - distance
        - duration
        - start_date
        - end_date
        - source
        - source_id
        - points
        - is_verified
        - polyline
        - calories
        - elevation_gain
        - average_heart_rate
        - max_heart_rate
        - created_at
        - updated_at
      filter:
        _or:
          - user_id:
              _eq: X-Hasura-User-Id
          - is_verified:
              _eq: true
insert_permissions:
  - role: user
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      set:
        user_id: X-Hasura-User-Id
        is_verified: false
      columns:
        - type
        - title
        - description
        - distance
        - duration
        - start_date
        - end_date
        - source
        - source_id
        - calories
        - elevation_gain
        - average_heart_rate
        - max_heart_rate
update_permissions:
  - role: user
    permission:
      columns:
        - title
        - description
      filter:
        _and:
          - user_id:
              _eq: X-Hasura-User-Id
          - is_verified:
              _eq: false
      check: null
